/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si.pegadaian.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import si.pegadaian.db.koneksiDatabase;

/**
 *
 * @author user-pc
 */
public class viewListDataBarang extends javax.swing.JFrame {
    public int id_barang=0;
    /**
     * Creates new form viewListDataPetugas
     */
    private viewFormTransaksi vFT;
    private DefaultTableModel model;
    private String sql="";
    public viewListDataBarang(viewFormTransaksi vFT) {
        initComponents();
        this.vFT=vFT;
        
        model=new DefaultTableModel();
        tabelListDataBarang.setModel(model);
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Type Barang");
        model.addColumn("Warna Barang");
        
        tampilDataBarang("");
    }

    public JTextField getCariTF() {
        return cariTF;
    }
    
    public void tampilDataBarang(String data){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        if(data.equals("")){
            sql= "SELECT * FROM barang";
        }else{
            sql="SELECT * FROM barang WHERE Nama_barang LIKE '"+data+"%'";
        }
        
        
        try{
            Statement stat=(Statement) koneksiDatabase.getKoneksi().createStatement();
            ResultSet res= stat.executeQuery(sql);
            
            
            while(res.next()){
                Object[] hasil;
                hasil =new Object[4];//karena ada 6 field ditabel pelanggan
                hasil[0]=res.getInt("Kode_barang");
                hasil[1]=res.getString("Nama_barang");
                hasil[2]=res.getString("Type");
                hasil[3]=res.getString("Warna");
                
                
                model.addRow(hasil);
                
            }
        } catch(SQLException ex){
            Logger.getLogger(viewBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cariTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelListDataBarang = new javax.swing.JTable();

        jLabel1.setText("Cari Nama Barang");

        cariTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTFActionPerformed(evt);
            }
        });
        cariTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariTFKeyPressed(evt);
            }
        });

        tabelListDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelListDataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelListDataBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelListDataBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTFActionPerformed

    private void cariTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTFKeyPressed
        // TODO add your handling code here:
        tampilDataBarang(cariTF.getText());
    }//GEN-LAST:event_cariTFKeyPressed

    private void tabelListDataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelListDataBarangMouseClicked
        // TODO add your handling code here:
        int ambilRow=tabelListDataBarang.getSelectedRow();
//        vFT.getCustomerTF().setText(tabelListDataPetugas.getValueAt(ambilRow, 0).toString());
        vFT.getBarangTF().setText(tabelListDataBarang.getValueAt(ambilRow,1).toString()/*+". "+tabelListDataBarang.getValueAt(ambilRow,1).toString()*/);
        String id = tabelListDataBarang.getValueAt(ambilRow,0).toString();
        id_barang = Integer.parseInt(id);
        vFT.getBarangTF().requestFocus();
        dispose();
    }//GEN-LAST:event_tabelListDataBarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelListDataBarang;
    // End of variables declaration//GEN-END:variables
}
