/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si.pegadaian.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import si.pegadaian.db.koneksiDatabase;

/**
 *
 * @author user-pc
 */
public class viewListDataGadai extends javax.swing.JFrame {

    /**
     * Creates new form viewListDataPetugas
     */
    public int idGadai;
    private viewFormTransaksi vFT;
    private DefaultTableModel model;
    private String sql="";
    public viewListDataGadai(viewFormTransaksi vFT) {
        initComponents();
        this.vFT=vFT;
        
        model=new DefaultTableModel();
        tabelListDataGadai.setModel(model);
        model.addColumn("ID");
        model.addColumn("Nama Petugas");
        model.addColumn("Nama Nasabah");
        model.addColumn("Kode Barang");
        model.addColumn("Tanggal Gadai");
        model.addColumn("Jatuh Tempo");
        model.addColumn("Jumlah Pinjaman");
        model.addColumn("Jumlah Tebusan");
        model.addColumn("Keterangan");

        tampilDataGadai("");
    }

    public JTextField getCariTF() {
        return cariTF;
    }
    
    public void tampilDataGadai(String data) {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        if (data.equals("")) {
            sql = "SELECT No_gadai,Nama_petugas,Nama_nasabah, Kode_barang, Tgl_gadai, Jatuh_tempo,Jumlah_pinjaman,Jumlah_tebusan,Keterangan "
                    + "FROM gadai gd, barang br, nasabah ns, petugas pt WHERE gd.Barang_Kode_barang=br.Kode_barang AND gd.Petugas_Nip=pt.Nip AND gd.Nasabah_Ktp=ns.Ktp AND Keterangan='Belum Ditebus' ";
        } else {
            sql = "SELECT No_gadai,Nama_petugas,Nama_nasabah, Kode_barang, Tgl_gadai, Jatuh_tempo,Jumlah_pinjaman,Jumlah_tebusan,Keterangan"
                    + " FROM gadai gd, barang br, nasabah ns, petugas pt "
                    + "WHERE gd.Barang_Kode_barang=br.Kode_barang "
                    + "AND gd.Petugas_Nip=pt.Nip "
                    + "AND gd.Nasabah_Ktp=ns.Ktp "
                    + "AND Keterangan LIKE '" + data + "%'";
        }

        try {
            Statement stat = (Statement) koneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);

            while (res.next()) {
                Object[] hasil;
                hasil = new Object[9];//karena ada 6 field ditabel pelanggan
                hasil[0] = res.getInt("No_gadai");
                hasil[1] = res.getString("Nama_petugas");
                hasil[2] = res.getString("Nama_nasabah");
                hasil[3] = res.getString("Kode_barang");
                hasil[4] = res.getString("Tgl_gadai");
                hasil[5] = res.getString("Jatuh_tempo");
                hasil[6] = res.getString("Jumlah_pinjaman");
                hasil[7] = res.getString("Jumlah_tebusan");
                hasil[8] = res.getString("Keterangan");

                model.addRow(hasil);

            }
        } catch (SQLException ex) {
            Logger.getLogger(viewBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cariTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelListDataGadai = new javax.swing.JTable();

        jLabel1.setText("Cari Nama Customer");

        cariTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTFActionPerformed(evt);
            }
        });
        cariTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariTFKeyPressed(evt);
            }
        });

        tabelListDataGadai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelListDataGadai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelListDataGadaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelListDataGadai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cariTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTFActionPerformed

    private void cariTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariTFKeyPressed
        // TODO add your handling code here:
        tampilDataGadai(cariTF.getText());
    }//GEN-LAST:event_cariTFKeyPressed

    private void tabelListDataGadaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelListDataGadaiMouseClicked
        // TODO add your handling code here:
        String date1;
        String pattern="yyyy-MM-dd";
        SimpleDateFormat sdf = new SimpleDateFormat(pattern);
        Date date = new Date();
        int ambilRow=tabelListDataGadai.getSelectedRow();
//        vFT.getCustomerTF().setText(tabelListDataPetugas.getValueAt(ambilRow, 0).toString());
        vFT.getJumlahPinjamanTF().setText(tabelListDataGadai.getValueAt(ambilRow,6).toString()/*+". "+tabelListDataCustomer.getValueAt(ambilRow,1).toString()*/);
        vFT.getJumlahTebusanTF().setText(tabelListDataGadai.getValueAt(ambilRow,7).toString()/*+". "+tabelListDataCustomer.getValueAt(ambilRow,1).toString()*/);
        vFT.getDataGadaiTF().setText(tabelListDataGadai.getValueAt(ambilRow,2).toString()/*+". "+tabelListDataCustomer.getValueAt(ambilRow,1).toString()*/);
        
        String g= tabelListDataGadai.getValueAt(ambilRow, 0).toString();
        idGadai= Integer.parseInt(g);
        vFT.getCustomerTF().requestFocus();
        dispose();
    }//GEN-LAST:event_tabelListDataGadaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelListDataGadai;
    // End of variables declaration//GEN-END:variables
}
