/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si.pegadaian.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import si.pegadaian.db.koneksiDatabase;

/**
 *
 * @author user-pc
 */
public class viewDataTransaksi extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewDataTransaksi
     */
    public DefaultTableModel modelTebus;
    public viewDataTransaksi() {
        initComponents();
        modelTebus=new DefaultTableModel();
        tabelDataTransaksi.setModel(modelTebus);
        modelTebus.addColumn("ID");
        modelTebus.addColumn("Nama Petugas");
        modelTebus.addColumn("Nama Nasabah");
        modelTebus.addColumn("Kode Barang");
        modelTebus.addColumn("Jatuh Tempo");
        modelTebus.addColumn("Tanggal Tebusan");
        modelTebus.addColumn("Jumlah Pinjaman");
        modelTebus.addColumn("Jumlah Tebusan");
        modelTebus.addColumn("Denda");
        modelTebus.addColumn("Total Tebusan");
        modelTebus.addColumn("Keterangan");
        
        tampilDataTransaksi();
    }
    
    public void tampilDataTransaksi(){
        modelTebus.getDataVector().removeAllElements();
        modelTebus.fireTableDataChanged();
        
        
        String sql= "SELECT No_gadai,Nama_petugas,Nama_nasabah, Kode_barang, Jatuh_tempo, Tgl_tebusan, Jumlah_pinjaman,Jumlah_tebusan,Denda, Total_tebusan, Keterangan "
                  + "FROM gadai gd, barang br, nasabah ns, petugas pt WHERE gd.Barang_Kode_barang=br.Kode_barang AND gd.Petugas_Nip=pt.Nip AND gd.Nasabah_Ktp=ns.Ktp ";
        
        try{
            Statement stat=(Statement) koneksiDatabase.getKoneksi().createStatement();
            ResultSet res= stat.executeQuery(sql);
            
            
            while(res.next()){
                Object[] hasil;
                hasil =new Object[11];//karena ada 6 field ditabel pelanggan
                hasil[0]=res.getInt("No_gadai");
                hasil[1]=res.getString("Nama_petugas");
                hasil[2]=res.getString("Nama_nasabah");
                hasil[3]=res.getString("Kode_barang");
                hasil[4]=res.getString("Jatuh_tempo");
                hasil[5]=res.getString("Tgl_tebusan");
                hasil[6]=res.getString("Jumlah_pinjaman");
                hasil[7]=res.getString("Jumlah_tebusan");
                hasil[8]=res.getString("Denda");
                hasil[9]=res.getString("Total_tebusan");
                hasil[10]=res.getString("Keterangan");

                modelTebus.addRow(hasil);
                
            }
        } catch(SQLException ex){
            Logger.getLogger(viewBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteBT = new javax.swing.JButton();
        refreshBT = new javax.swing.JButton();
        cetakCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataTransaksi = new javax.swing.JTable();

        setClosable(true);

        deleteBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-property-32.png"))); // NOI18N
        deleteBT.setText("Delete");

        refreshBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sinchronize-32.png"))); // NOI18N
        refreshBT.setText("Refresh");

        cetakCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Cetak Berdasarkan--" }));

        tabelDataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelDataTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteBT)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBT)
                        .addGap(27, 27, 27)
                        .addComponent(cetakCB, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBT)
                    .addComponent(refreshBT)
                    .addComponent(cetakCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cetakCB;
    private javax.swing.JButton deleteBT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBT;
    private javax.swing.JTable tabelDataTransaksi;
    // End of variables declaration//GEN-END:variables
}
